// CsvAnalyze — port of CsvLint/CsvAnalyze.cs + CsvAnalyzeColumn.cs:
// separator inference by per-line character-frequency variance, fixed-width
// column detection, per-column datatype/width/mask inference, statistics
// report and unique-value counting. Pure functions over document text — the
// plugin feeds Scintilla text in, results come back as data/strings.
#pragma once
#include <string>
#include <vector>
#include "CsvDefinition.h"

/// Per-column statistics accumulator (CsvAnalyzeColumn.cs).
struct CsvAnalyzeColumn {
    std::string Name;
    int Index = 0;
    int MinWidth = 9999, MaxWidth = 0;
    int CountAll = 0, CountEmpty = 0, CountString = 0, CountInteger = 0;
    int CountDecimal = 0, CountDecimalComma = 0, CountDecimalPoint = 0;
    int DecimalDigMax = 0, DecimalDecMax = 0, DecimalIntMax = 0;
    int CountDateTime = 0;
    char DateSep = '\0';
    int DateMax1 = 0, DateMax2 = 0, DateMax3 = 0;

    // full stats
    long long stat_minint = 0, stat_maxint = 0;
    double stat_mindbl = 0.0, stat_maxdbl = 0.0;
    long long stat_mindat_key = 0, stat_maxdat_key = 0;
    std::string stat_minint_org, stat_maxint_org;
    std::string stat_mindbl_org, stat_maxdbl_org;
    std::string stat_mindat_org, stat_maxdat_org;
    int stat_dat_dmy = 0;             // 0=unknown 1=YMD 2=DMY 3=MDY
    std::string stat_dat_format;
    std::vector<std::pair<std::string, int>> stat_uniquecount;  // first-seen order

    explicit CsvAnalyzeColumn(int idx) : Index(idx) {}

    void InputData(std::string data, bool fullstats);
    void DateTimeFormatKnown(const std::string &knownformat);
    CsvColumn InferDatatype();

private:
    void KeepMinMaxInteger(const std::string &value);
    void KeepMinMaxDecimal(const std::string &value, char dec);
    void KeepMinMaxDateTime(const std::string &value, int dd1, int dd2, int dd3, int datatype);
    void KeepUniqueValues(const std::string &value);
    bool CountDataTypeSignificant(int c1, int c2, int c3, int c4) const;
};

namespace CsvAnalyze {

/// Infer CSV definition from data (CsvAnalyze.InferFromData). `text` is the
/// full document content.
CsvDefinition InferFromData(const std::string &text,
                            bool autodetect, char mansep, const std::string &manwid,
                            bool manhead, int manskip, char commchar,
                            bool userRequested, bool isCsv);

/// Analyse-data-report text (StatisticalReportData minus the host calls).
/// `commentLines` = the "generated by" header lines from the caller.
std::string StatisticalReport(const std::string &text, CsvDefinition &csvdef,
                              const std::vector<std::string> &commentLines);

/// Unique-value counting for Select columns (CountUniqueValues): returns the
/// generated CSV content and fills `csvnew` with the output definition.
std::string CountUniqueValues(const std::string &text, CsvDefinition &csvdef,
                              const std::vector<int> &colidx, bool sortBy, bool sortAsc,
                              CsvDefinition &csvnew);

}  // namespace CsvAnalyze
